# runtime: custom
# env: flex

# runtime_config:
#   python_version: 3

# # automatic_scaling:
# #   max_instances: 2
# #   target_cpu_utilization: 0.9
# #   max_concurrent_requests: 40
# resources:
#   cpu: 4
#   memory_gb: 10
#   disk_size_gb: 20


# entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app --timeout 240
